// Generated by https://github.com/sashamakarenko/fixpp
// Copyright (c) 2021 sashamakarenko
// https://github.com/sashamakarenko/fixpp/blob/main/LICENSE
#pragma once
#ifndef order_MESSAGE_BUILDERS_H
#define order_MESSAGE_BUILDERS_H

#include <order/SenderApi.h>


namespace order
{

// start of MessageBuilders.hxx

// Group LegStipulations
class LegStipulationsBuilder : protected ReusableMessageBuilder
{
   public:
     void appendLegStipulationType( const std::string_view & value ){ appendSafely<FieldLegStipulationType>( value ); }
     void appendLegStipulationValue( const std::string_view & value ){ appendSafely<FieldLegStipulationValue>( value ); }
};


// Group NestedPartySubIDs
class NestedPartySubIDsBuilder : protected ReusableMessageBuilder
{
   public:
     void appendNestedPartySubID( const std::string_view & value ){ appendSafely<FieldNestedPartySubID>( value ); }
     void appendNestedPartySubIDType( const int & value ){ appendSafely<FieldNestedPartySubIDType>( value ); }
};


// Group NestedPartyIDs
class NestedPartyIDsBuilder : protected ReusableMessageBuilder
{
   public:
     void appendNestedPartyID( const std::string_view & value ){ appendSafely<FieldNestedPartyID>( value ); }
     void appendNestedPartyIDSource( const char & value ){ appendSafely<FieldNestedPartyIDSource>( value ); }
     void appendNestedPartyRole( const int & value ){ appendSafely<FieldNestedPartyRole>( value ); }
     NestedPartySubIDsBuilder & appendNoNestedPartySubIDs( unsigned count ) { appendSafely<FieldNoNestedPartySubIDs>( count ); return *reinterpret_cast<NestedPartySubIDsBuilder*>( this ); }
};


// Group Legs
class LegsBuilder : protected ReusableMessageBuilder
{
   public:
     void appendLegSymbol( const std::string_view & value ){ appendSafely<FieldLegSymbol>( value ); }
     void appendLegSide( const char & value ){ appendSafely<FieldLegSide>( value ); }
     void appendLegQty( const Float & value ){ appendSafely<FieldLegQty>( value ); }
     LegStipulationsBuilder & appendNoLegStipulations( unsigned count ) { appendSafely<FieldNoLegStipulations>( count ); return *reinterpret_cast<LegStipulationsBuilder*>( this ); }
     void appendLegPositionEffect( const char & value ){ appendSafely<FieldLegPositionEffect>( value ); }
     NestedPartyIDsBuilder & appendNoNestedPartyIDs( unsigned count ) { appendSafely<FieldNoNestedPartyIDs>( count ); return *reinterpret_cast<NestedPartyIDsBuilder*>( this ); }
     void appendLegRefID( const std::string_view & value ){ appendSafely<FieldLegRefID>( value ); }
     void appendLegPrice( const Float & value ){ appendSafely<FieldLegPrice>( value ); }
     void appendLegLastPx( const Float & value ){ appendSafely<FieldLegLastPx>( value ); }
};


// Message Header
class HeaderBuilder: public HeaderTemplate
{
   public:

     void appendBeginString( const std::string_view & value ){ append<FieldBeginString>( value ); }
     void appendBodyLength( const unsigned & value ){ append<FieldBodyLength>( value ); }
     void appendMsgType( const std::string_view & value ){ append<FieldMsgType>( value ); }
     void appendSenderCompID( const std::string_view & value ){ append<FieldSenderCompID>( value ); }
     void appendTargetCompID( const std::string_view & value ){ append<FieldTargetCompID>( value ); }
     void appendMsgSeqNum( const unsigned & value ){ append<FieldMsgSeqNum>( value ); }
     void appendSendingTime( const std::string_view & value ){ append<FieldSendingTime>( value ); }
};


// Message NewOrderSingle
class NewOrderSingleBuilder: protected ReusableMessageBuilder
{
   public:

     static NewOrderSingleBuilder & coat( ReusableMessageBuilder & builder ){ return reinterpret_cast<NewOrderSingleBuilder&>( builder ); }
     HeaderBuilder & getHeader(){ return reinterpret_cast<HeaderBuilder&>( header ); }
     ReusableMessageBuilder & super(){ return *this; }
     void appendClOrdID( const std::string_view & value ){ appendSafely<FieldClOrdID>( value ); }
     void appendAccount( const std::string_view & value ){ appendSafely<FieldAccount>( value ); }
     void appendSymbol( const std::string_view & value ){ appendSafely<FieldSymbol>( value ); }
     void appendSecurityID( const std::string_view & value ){ appendSafely<FieldSecurityID>( value ); }
     void appendSide( const char & value ){ appendSafely<FieldSide>( value ); }
     void appendQtyType( const int & value ){ appendSafely<FieldQtyType>( value ); }
     void appendOrderQty( const Float & value ){ appendSafely<FieldOrderQty>( value ); }
     void appendOrdType( const char & value ){ appendSafely<FieldOrdType>( value ); }
     void appendPrice( const Float & value ){ appendSafely<FieldPrice>( value ); }
     void appendStopPx( const Float & value ){ appendSafely<FieldStopPx>( value ); }
     void appendTransactTime( const std::string_view & value ){ appendSafely<FieldTransactTime>( value ); }
};


// Message ExecutionReport
class ExecutionReportBuilder: protected ReusableMessageBuilder
{
   public:

     static ExecutionReportBuilder & coat( ReusableMessageBuilder & builder ){ return reinterpret_cast<ExecutionReportBuilder&>( builder ); }
     HeaderBuilder & getHeader(){ return reinterpret_cast<HeaderBuilder&>( header ); }
     ReusableMessageBuilder & super(){ return *this; }
     void appendOrderID( const std::string_view & value ){ appendSafely<FieldOrderID>( value ); }
     void appendClOrdID( const std::string_view & value ){ appendSafely<FieldClOrdID>( value ); }
     void appendOrigClOrdID( const std::string_view & value ){ appendSafely<FieldOrigClOrdID>( value ); }
     void appendExecID( const std::string_view & value ){ appendSafely<FieldExecID>( value ); }
     void appendExecType( const char & value ){ appendSafely<FieldExecType>( value ); }
     void appendOrdStatus( const char & value ){ appendSafely<FieldOrdStatus>( value ); }
     void appendOrdRejReason( const int & value ){ appendSafely<FieldOrdRejReason>( value ); }
     void appendAccount( const std::string_view & value ){ appendSafely<FieldAccount>( value ); }
     void appendSymbol( const std::string_view & value ){ appendSafely<FieldSymbol>( value ); }
     void appendSecurityID( const std::string_view & value ){ appendSafely<FieldSecurityID>( value ); }
     void appendSecurityType( const std::string_view & value ){ appendSafely<FieldSecurityType>( value ); }
     void appendText( const std::string_view & value ){ appendSafely<FieldText>( value ); }
     void appendProduct( const int & value ){ appendSafely<FieldProduct>( value ); }
     void appendSide( const char & value ){ appendSafely<FieldSide>( value ); }
     void appendQtyType( const int & value ){ appendSafely<FieldQtyType>( value ); }
     void appendOrderQty( const Float & value ){ appendSafely<FieldOrderQty>( value ); }
     void appendOrdType( const char & value ){ appendSafely<FieldOrdType>( value ); }
     void appendPriceType( const int & value ){ appendSafely<FieldPriceType>( value ); }
     void appendPrice( const Float & value ){ appendSafely<FieldPrice>( value ); }
     void appendStopPx( const Float & value ){ appendSafely<FieldStopPx>( value ); }
     void appendCurrency( const std::string_view & value ){ appendSafely<FieldCurrency>( value ); }
     void appendTimeInForce( const char & value ){ appendSafely<FieldTimeInForce>( value ); }
     void appendExecInst( const std::string_view & value ){ appendSafely<FieldExecInst>( value ); }
     void appendLastQty( const Float & value ){ appendSafely<FieldLastQty>( value ); }
     void appendLastPx( const Float & value ){ appendSafely<FieldLastPx>( value ); }
     void appendLeavesQty( const Float & value ){ appendSafely<FieldLeavesQty>( value ); }
     void appendAvgPx( const Float & value ){ appendSafely<FieldAvgPx>( value ); }
     void appendCumQty( const Float & value ){ appendSafely<FieldCumQty>( value ); }
     LegsBuilder & appendNoLegs( unsigned count ) { appendSafely<FieldNoLegs>( count ); return *reinterpret_cast<LegsBuilder*>( this ); }
};
// end of MessageBuilders.hxx

} // namespace order

#endif /* order_MESSAGE_BUILDERS_H */

