//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.23 at 12:13:01 PM CET 
//


package phix.xml2cpp.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fieldOrComponentOrGroup"
})
@XmlRootElement(name = "message")
public class Message {

    @XmlAttribute(name = "name")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "msgtype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String msgtype;
    @XmlAttribute(name = "msgcat")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String msgcat;
    @XmlElements({
        @XmlElement(name = "field", type = Field.class),
        @XmlElement(name = "component", type = Component.class),
        @XmlElement(name = "group", type = Group.class)
    })
    protected List<Object> fieldOrComponentOrGroup;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the msgtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgtype() {
        return msgtype;
    }

    /**
     * Sets the value of the msgtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgtype(String value) {
        this.msgtype = value;
    }

    /**
     * Gets the value of the msgcat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgcat() {
        return msgcat;
    }

    /**
     * Sets the value of the msgcat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgcat(String value) {
        this.msgcat = value;
    }

    /**
     * Gets the value of the fieldOrComponentOrGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldOrComponentOrGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldOrComponentOrGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * {@link Component }
     * {@link Group }
     * 
     * 
     */
    public List<Object> getFieldOrComponentOrGroup() {
        if (fieldOrComponentOrGroup == null) {
            fieldOrComponentOrGroup = new ArrayList<Object>();
        }
        return this.fieldOrComponentOrGroup;
    }

}
